language: node_js

branches:
  only:
    - master

cache: yarn

node_js: 8

script: node .

after_success:
  - yarn global add semantic-release
  - 'semantic-release pre &&
    yarn publish --new-version `yarn run -s print-version` &&
    semantic-release post'

